[ci] Fix unbound variable problem

diff --git a/ci/scripts/testflight b/ci/scripts/testflight
--- a/ci/scripts/testflight
+++ b/ci/scripts/testflight
@@ -56,20 +56,21 @@ if [[ ! -z $DEBUG ]]; then
 	echo "Variables passed to deployment manifest:"
 	cat tmp/vars.yml
 fi
-	cat tmp/vars.yml
 # convert YAML to JSON to check YAML validity
 spruce json tmp/vars.yml > /dev/null
 
-echo "Confirming each operator file exists: ${MANIFEST_OP_PATHS:-ok, none specified.}"
-op_patch_file_errors=
-for op_patch_file in ${MANIFEST_OP_PATHS//,/ } ; do
-	if [[ ! -f $op_patch_file ]]; then
-		op_patch_file_errors=1
-		echo "Operator file missing: ${op_patch_file}"
+if [[ -n "${MANIFEST_OP_PATHS:-}" ]]; then
+	echo "Confirming each operator file exists: ${MANIFEST_OP_PATHS}"
+	op_patch_file_errors=
+	for op_patch_file in ${MANIFEST_OP_PATHS//,/ } ; do
+		if [[ ! -f $op_patch_file ]]; then
+			op_patch_file_errors=1
+			echo "Operator file missing: ${op_patch_file}"
+		fi
+	done
+	if [[ ! -z ${op_patch_file_errors} ]]; then
+		exit 1
 	fi
-done
-if [[ ! -z ${op_patch_file_errors} ]]; then
-	exit 1
 fi
 
 $DIR/wait-until-proxy-bosh-cf-running
@@ -139,11 +140,11 @@ YAML
 done
 
 op_patch_files_flags=""
-for op_patch_file in ${MANIFEST_OP_PATHS//,/ } ; do
+if [[ -n "${MANIFEST_OP_PATHS:-}" ]]; then
+  for op_patch_file in ${MANIFEST_OP_PATHS//,/ } ; do
    op_patch_files_flags="${op_patch_files_flags} -o $op_patch_file"
-done
-
-set -x
+  done
+fi
 
 bosh int ${MANIFEST_PATH} \
   -o tmp/deployment.yml    \
